### ISSUE TITLE
Error with UTF8 filenames

### ISSUE THREAD

**Issue by lyoshenka** [lyoshenka/begemot#9]
### Repro steps
1. Use UTF8 characters in email title. "가나다라1234abcd" for example
1. post

### Expected
Document url is "가나다라1234abcd.html" 

### Actual
Server error

### Error message

```Error creating file on github: exception 'Github\Exception\RuntimeException' with message 'Server Error' in /home/grin/begemot/vendor/knplabs/github-api/lib/Github/HttpClient/Listener/ErrorListener.php:92 
Stack trace: 
#0 [internal function]: Github\HttpClient\Listener\ErrorListener->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) 
#1 /home/grin/begemot/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) 
#2 /home/grin/begemot/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event)) 
#3 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event)) 
#4 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array) 
#5 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array) 
#6 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array) 
#7 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) 
#8 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages() 
#9 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles() 
#10 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform() 
#11 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send() 
#12 /home/grin/begemot/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send() 
#13 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php(140): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest)) 
#14 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php(129): Github\HttpClient\HttpClient->request('repos/lyoshenka...', '{"content":"LS0...', 'PUT', Array) 
#15 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php(167): Github\HttpClient\HttpClient->put('repos/lyoshenka...', '{"content":"LS0...', Array) 
#16 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/Api/Repository/Contents.php(93): Github\Api\AbstractApi->put('repos/lyoshenka...', Array) 
#17 /home/grin/begemot/app/routes/main.php(189): Github\Api\Repository\Contents->create('lyoshenka', 'grinfit', '_posts/2018-05-...', '---?title: ????...', 'post via begemo...', 'master', Array) 
#18 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) 
#19 /home/grin/begemot/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) 
#20 /home/grin/begemot/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#21 /home/grin/begemot/vendor/silex/silex/src/Silex/Application.php(538): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#22 /home/grin/begemot/vendor/silex/silex/src/Silex/Application.php(515): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request
#23 /home/grin/begemot/web/index.php(4): Silex\Application->run() 
#24 {main}  
Next exception 'Github\Exception\RuntimeException' with message 'Server Error' in /home/grin/begemot/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php:146 
Stack trace: 
#0 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/HttpClient/HttpClient.php(129): Github\HttpClient\HttpClient->request('repos/lyoshenka...', '{"content":"LS0...', 'PUT', Array) 
#1 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php(167): Github\HttpClient\HttpClient->put('repos/lyoshenka...', '{"content":"LS0...', Array) 
#2 /home/grin/begemot/vendor/knplabs/github-api/lib/Github/Api/Repository/Contents.php(93): Github\Api\AbstractApi->put('repos/lyoshenka...', Array) 
#3 /home/grin/begemot/app/routes/main.php(189): Github\Api\Repository\Contents->create('lyoshenka', 'grinfit', '_posts/2018-05-...', '---?title: ????...', 'post via begemo...', 'master', Array) 
#4 [internal function]: {closure}(Object(Symfony\Component\HttpFoundation\Request)) 
#5 /home/grin/begemot/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(145): call_user_func_array(Object(Closure), Array) 
#6 /home/grin/begemot/vendor/symfony/http-kernel/Symfony/Component/HttpKernel/HttpKernel.php(66): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#7 /home/grin/begemot/vendor/silex/silex/src/Silex/Application.php(538): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#8 /home/grin/begemot/vendor/silex/silex/src/Silex/Application.php(515): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#9 /home/grin/begemot/web/index.php(4): Silex\Application->run() 
#10 {main} [] []
```

**Comment by arthrfrts** [comment]
Just tested creating a post with `çãá` on the subject and indeed still got this error.
